services:
  mt5:
    build: .
    image: gmag11/metatrader5_vnc
    container_name: mt5
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
    volumes:
      - mt5-config:/config
    env_file:
      - .env
volumes:
  mt5-config:
