services:
  mt5:
    build: .
    image: gmag11/metatrader5_vnc
    container_name: mt5
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - mt5-config:/config
    env_file:
      - .env
volumes:
  mt5-config:
